import jane from "../assets/jane.png";
import doc1 from "../assets/d1.jpg";
import doc2 from "../assets/d2.jpg";
import doc3 from "../assets/d3.jpg";
import doc4 from "../assets/d3.jpg";
import assetsData from "../assets/assetsData";

export const doctors = [
  {
    id: 176897,
    name: "Dr. Elina Josh",
    email: "elina@hospital.com",
    password: "doctor123",
    role: "doctor",
    specialization: "Cardiology",
    availability: [
      { date: "2025-08-11", slots: ["11:00", "13:00", "15:00"] },
      { date: "2025-08-12", slots: ["09:30", "12:00", "14:30"] },
    ],

    years_experience: 15,
    demo_image: assetsData.teamImage3,
    social_media: { linkedin: "#", twitter: "#", instagram: "#" },
    rating: 4.5,
    qualification: "MBBS, MD, DM Cardiology",
  },
  {
    id: 276567,
    name: "Dr. Laxman Sinha",
    email: "laxman@hospital.com",
    password: "doctor456",
    role: "doctor",
    specialization: "Orthopedic",
    availability: [
      { date: "2025-08-11", slots: ["09:00", "10:30", "14:00"] },
      { date: "2025-08-12", slots: ["10:00", "11:30", "16:00"] },
    ],

    years_experience: 15,
    demo_image: doc1,
    social_media: { linkedin: "#", twitter: "#", instagram: "#" },
    rating: 4.2,
    qualification: "MBBS, MS Orthopedics",
  },
  {
    id: 102032,
    name: "Dr. Emily Carter",
    email: "emily@hospital.com",
    password: "doctor789",
    role: "doctor",
    specialization: "Dermatology",
    availability: [
      { date: "2025-08-11", slots: ["09:00", "10:30", "14:00"] },
      { date: "2025-08-12", slots: ["10:00", "11:30", "16:00"] },
    ],
    years_experience: 15,

    demo_image: doc2,
    social_media: { linkedin: "#", twitter: "#", instagram: "#" },
    rating: 4.7,
    qualification: "MBBS, MD, DM Cardiology",
  },
  {
    id: 202032,
    name: "Dr. Mia Mike",
    email: "mia@hospital.com",
    password: "doctor321",
    role: "doctor",
    specialization: "ENT Specialist",
    availability: [
      { date: "2025-08-11", slots: ["11:00", "13:00", "15:00"] },
      { date: "2025-08-12", slots: ["09:30", "12:00", "14:30"] },
    ],
    years_experience: 7,
    demo_image: doc3,
    social_media: { linkedin: "#", twitter: "#", instagram: "#" },
    rating: 4.3,
    qualification: "MBBS, MS ENT",
  },
  {
    id: 302032,
    name: "Dr. Adam Smith",
    email: "adam@hospital.com",
    password: "doctor654",
    role: "doctor",
    specialization: "Dermatology",
    availability: [
      { date: "2025-08-11", slots: ["11:00", "13:00", "15:00"] },
      { date: "2025-08-12", slots: ["09:30", "12:00", "14:30"] },
    ],
    years_experience: 7,
    demo_image: doc4,
    social_media: { linkedin: "#", twitter: "#", instagram: "#" },
    rating: 4.1,
    qualification: "MBBS, MD Dermatology",
  },
  {
    id: 402032,
    name: "Dr. Asha Sing",
    email: "asha@hospital.com",
    password: "doctor987",
    role: "doctor",
    specialization: "Orthopedics",
    availability: [
      { date: "2025-08-11", slots: ["11:00", "13:00", "15:00"] },
      { date: "2025-08-12", slots: ["09:30", "12:00", "14:30"] },
    ],
    years_experience: 5,
    demo_image: doc4,
    social_media: { linkedin: "#", twitter: "#", instagram: "#" },
    rating: 4.0,
    qualification: "MBBS, MS Orthopedics",
  },
  {
    id: 502032,
    name: "Dr. Smith",
    email: "smith@hospital.com",
    password: "doctor123",
    role: "doctor",
    specialization: "Cardiology",
    availability: [
      { date: "2025-08-16", slots: ["09:00", "11:00", "14:00"] },
      { date: "2025-08-17", slots: ["10:00", "12:00", "15:00"] },
    ],
    years_experience: 7,
    demo_image: doc3,
    social_media: { linkedin: "#", twitter: "#", instagram: "#" },
    rating: 3.72,
    qualification: "MBBS, MD",
  },
];

export const patients = [
  {
    id: 101,
    name: "Ravi Kumar",
    email: "ravi@gmail.com",
    password: "patient123",
    age: 28,
    gender: "Male",
    dob: "04/12/2003",
    bloodType: "B+",
    phone: "+919876543210",
    address: "123 Main St, Bangalore",
    demo_image: assetsData.BoyAvatar,
  },
  {
    id: 102,
    name: "Priya Sharma",
    email: "priya@gmail.com",
    password: "patient123",
    age: 32,
    gender: "Female",
    bloodType: "A-",
    dob: "04/12/2003",
    phone: "+919876543211",
    address: "456 Oak Ave, Mumbai",
    demo_image: assetsData.profile1,
  },
  {
    id: 103,
    name: "Amit Patel",
    email: "amit@gmail.com",
    password: "patient123",
    age: 45,
    gender: "Male",
    dob: "04/12/2003",
    bloodType: "O+",
    phone: "+919876543212",
    address: "789 Pine Rd, Delhi",
    demo_image: assetsData.profile,
  },
  {
    id: 104,
    name: "Neha Gupta",
    email: "neha@gmail.com",
    password: "patient123",
    age: 29,
    gender: "Female",
    dob: "04/12/2003",
    bloodType: "AB+",
    phone: "+919876543213",
    address: "321 Elm St, Hyderabad",
    demo_image: assetsData.profile,
  },
  {
    id: 105,
    name: "Rajesh Verma",
    email: "rajesh@gmail.com",
    password: "patient123",
    age: 50,
    gender: "Male",
    bloodType: "A+",
    phone: "+919876543214",
    dob: "04/12/2003",
    address: "654 Maple Dr, Chennai",
    demo_image: assetsData.profile,
  },
  {
    id: 106,
    name: "Sunita Yadav",
    email: "sunita@gmail.com",
    password: "patient123",
    age: 38,
    gender: "Female",
    bloodType: "B-",
    dob: "04/12/2003",
    phone: "+919876543215",
    address: "987 Cedar Ln, Kolkata",
    demo_image: assetsData.profile,
  },
  {
    id: 107,
    name: "Vikram Singh",
    email: "vikram@gmail.com",
    password: "patient123",
    age: 42,
    gender: "Male",
    bloodType: "O-",
    phone: "+919876543216",
    dob: "04/12/2003",
    address: "147 Birch Blvd, Pune",
    demo_image: assetsData.profile,
  },
  {
    id: "HO132",
    name: "Jane",
    email: "jane@gmail.com",
    password: "patient123",
    age: 21,
    gender: "Female",
    bloodType: "B+",
    phone: "+919876543217",
    address: "DLF CyberCity, Hyderabad, Telangana",
    dob: "04/12/2003",
    demo_image: jane,
    dist: "Hyderabad",
    state: "Telangana",
  },
];

export const appointments = [
  {
    id: 1,
    doctorId: 176897,
    doctorName: "Dr. Asha Singh",
    patientId: 101,
    patientName: "Ravi Kumar",
    date: "2025-08-15",
    time: "10:00",
    status: "CONFIRMED",
    reason: "Regular checkup",
    specialty: "Cardiology",
    consultationId: "cons001",
  },
  {
    id: 2,
    doctorId: 276567,
    doctorName: "Dr. Laxman Sinha",
    patientId: 101,
    patientName: "Ravi Kumar",
    date: "2025-08-26",
    time: "11:30",
    status: "PENDING",
    reason: "Knee pain consultation",
    specialty: "Orthopedic",
  },
  {
    id: 3,
    doctorId: 102032,
    doctorName: "Dr. Emily Carter",
    patientId: 102,
    patientName: "Priya Sharma",
    date: "2025-08-17",
    time: "14:00",
    status: "REJECTED",
    reason: "Heart condition follow-up",
    specialty: "Cardiology",
    consultationId: "cons002",
  },
  {
    id: 4,
    doctorId: 202032,
    doctorName: "Dr. Adam Smith",
    patientId: 103,
    patientName: "Amit Patel",
    date: "2025-08-14",
    time: "09:00",
    status: "COMPLETED",
    reason: "Sinus infection",
    specialty: "ENT",
    consultationId: "cons003",
  },
  {
    id: 5,
    doctorId: 302032,
    doctorName: "Dr. Mia Mike",
    patientId: 104,
    patientName: "Neha Gupta",
    date: "2025-08-18",
    time: "15:30",
    status: "CONFIRMED",
    reason: "Skin allergy",
    specialty: "Dermatology",
    consultationId: "cons004",
  },
  {
    id: 6,
    doctorId: 402032,
    doctorName: "Dr. Elina Josh",
    patientId: 105,
    patientName: "Rajesh Verma",
    date: "2025-08-13",
    time: "16:00",
    status: "CANCELLED",
    reason: "Back pain consultation",
    specialty: "Orthopedics",
  },
  {
    id: 7,
    doctorId: 176897,
    doctorName: "Dr. Asha Singh",
    patientId: 106,
    patientName: "Sunita Yadav",
    date: "2025-08-19",
    time: "10:30",
    status: "PENDING",
    reason: "Blood pressure check",
    specialty: "Cardiology",
  },
  {
    id: 8,
    doctorId: 202032,
    doctorName: "Dr. Adam Smith",
    patientId: 107,
    patientName: "Vikram Singh",
    date: "2025-08-12",
    time: "11:00",
    status: "COMPLETED",
    reason: "Hearing test",
    specialty: "ENT",
    consultationId: "cons005",
  },
  {
    id: 9,
    doctorId: 176897,
    doctorName: "Dr. Asha Singh",
    patientId: 101,
    patientName: "Ravi Kumar",
    date: "2025-08-15",
    time: "10:00",
    status: "CONFIRMED",
    reason: "Regular checkup",
    specialty: "Cardiology",
  },
  {
    id: 10,
    doctorId: 176897,
    doctorName: "Dr. Asha Singh",
    patientId: 106,
    patientName: "Sunita Yadav",
    date: "2025-08-19",
    time: "10:30",
    status: "PENDING",
    reason: "Blood pressure check",
    specialty: "Cardiology",
  },
  {
    id: 11,
    doctorId: 176897,
    doctorName: "Dr. Asha Singh",
    patientId: 101,
    patientName: "Ravi Kumar",
    date: "2025-08-15",
    time: "10:00",
    status: "CONFIRMED",
    reason: "Regular checkup",
    specialty: "Cardiology",
  },
  {
    id: 12,
    doctorId: 176897,
    doctorName: "Dr. Asha Singh",
    patientId: 102,
    patientName: "Priya Sharma",
    date: "2025-08-17",
    time: "14:00",
    status: "REJECTED",
    reason: "Heart condition follow-up",
    specialty: "Cardiology",
  },
  {
    id: 13,
    doctorId: 502032,
    doctorName: "Dr. Smith",
    patientId: "HO132",
    patientName: "Jane",
    date: "2025-08-16",
    time: "11:00",
    status: "COMPLETED",
    reason: "Persistent cough",
    specialty: "Cardiology",
    consultationId: "cons006",
    symptoms: "Cough",
    bloodPressure: 100,
    height: 200,
    weight: 67,
  },
  {
    id: 14,
    doctorId: 502032,
    doctorName: "Dr. Smith",
    patientId: "HO132",
    patientName: "Jane",
    date: "2025-07-10",
    time: "10:00",
    status: "COMPLETED",
    reason: "Fever and sore throat",
    specialty: "Cardiology",
    consultationId: "cons007",
    symptoms: "Fever, sore throat",
    bloodPressure: 110,
    height: 200,
    weight: 65,
  },
];

export const consultations = [
  {
    id: "cons001",
    appointmentId: 1,
    patientId: 101,
    doctorId: 176897,
    date: "2025-08-15",
    symptoms: "Headache, dizziness",
    bloodPressure: 140,
    height: 175,
    weight: 80,
    description:
      "Patient reported persistent headaches and occasional dizziness.",
    notes:
      "Blood pressure elevated. Recommended lifestyle modifications and follow-up.",
    prescription: [
      {
        medicine: "Amlodipine",
        dosage: "5mg",
        frequency: "Once daily",
        duration: "30 days",
      },
    ],
    followUpDate: "2025-09-15",
    status: "FOLLOWUP_NEEDED",
  },
  {
    id: "cons002",
    appointmentId: 3,
    patientId: 102,
    doctorId: 102032,
    date: "2025-08-17",
    symptoms: "Chest pain, palpitations",
    bloodPressure: 130,
    height: 160,
    weight: 55,
    description: "Patient reported intermittent chest pain and palpitations.",
    notes: "ECG shows occasional PVCs. Recommended Holter monitoring.",
    prescription: [
      {
        medicine: "Metoprolol",
        dosage: "25mg",
        frequency: "Twice daily",
        duration: "14 days",
      },
    ],
    followUpDate: "2025-08-31",
    status: "FOLLOWUP_NEEDED",
  },
  {
    id: "cons003",
    appointmentId: 4,
    patientId: 103,
    doctorId: 202032,
    date: "2025-08-14",
    symptoms: "Nasal congestion, headache",
    bloodPressure: 120,
    height: 170,
    weight: 70,
    description:
      "Patient with 5-day history of nasal congestion and facial pain.",
    notes:
      "Diagnosed with acute sinusitis. Recommended saline nasal irrigation.",
    prescription: [
      {
        medicine: "Amoxicillin-Clavulanate",
        dosage: "625mg",
        frequency: "Twice daily",
        duration: "7 days",
      },
      {
        medicine: "Pseudoephedrine",
        dosage: "60mg",
        frequency: "Every 6 hours",
        duration: "5 days",
      },
    ],
    followUpDate: null,
    status: "COMPLETED",
  },
  {
    id: "cons004",
    appointmentId: 5,
    patientId: 104,
    doctorId: 302032,
    date: "2025-08-18",
    symptoms: "Itchy rash on arms",
    bloodPressure: 115,
    height: 165,
    weight: 60,
    description:
      "Patient presented with pruritic erythematous rash on both forearms.",
    notes:
      "Allergic contact dermatitis suspected. Recommended allergen avoidance.",
    prescription: [
      {
        medicine: "Hydrocortisone cream",
        dosage: "1%",
        frequency: "Apply twice daily",
        duration: "7 days",
      },
      {
        medicine: "Cetirizine",
        dosage: "10mg",
        frequency: "Once daily at bedtime",
        duration: "7 days",
      },
    ],
    followUpDate: null,
    status: "COMPLETED",
  },
  {
    id: "cons005",
    appointmentId: 8,
    patientId: 107,
    doctorId: 202032,
    date: "2025-08-12",
    symptoms: "Hearing difficulty",
    bloodPressure: 125,
    height: 180,
    weight: 75,
    description:
      "Patient reports gradual hearing loss in right ear over 6 months.",
    notes: "Audiometry confirms mild conductive hearing loss. CT scan ordered.",
    prescription: [],
    followUpDate: "2025-09-12",
    status: "FOLLOWUP_NEEDED",
  },
  {
    id: "cons006",
    appointmentId: 13,
    patientId: "HO132",
    doctorId: 502032,
    date: "2025-08-16",
    symptoms: "Cough",
    bloodPressure: 100,
    height: 200,
    weight: 67,
    description:
      "Patient presented with persistent cough for 1 week. No fever.",
    notes: "Lungs clear to auscultation. Suspected post-viral cough.",
    prescription: [
      {
        medicine: "Dextromethorphan",
        dosage: "15mg",
        frequency: "Every 6 hours as needed",
        duration: "5 days",
      },
    ],
    followUpDate: "2025-08-23",
    status: "COMPLETED",
  },
  {
    id: "cons007",
    appointmentId: 14,
    patientId: "HO132",
    doctorId: 502032,
    date: "2025-07-10",
    symptoms: "Fever, sore throat",
    bloodPressure: 110,
    height: 200,
    weight: 65,
    description:
      "Patient with 3-day history of fever (max 101°F) and painful swallowing.",
    notes: "Pharynx erythematous with no exudate. Rapid strep test negative.",
    prescription: [
      {
        medicine: "Acetaminophen",
        dosage: "500mg",
        frequency: "Every 6 hours as needed",
        duration: "3 days",
      },
      {
        medicine: "Warm salt water gargles",
        dosage: "",
        frequency: "3 times daily",
        duration: "5 days",
      },
    ],
    followUpDate: null,
    status: "COMPLETED",
  },
];

export const patientHistory = [
  {
    id: 1,
    consultationId: "cons001",
    patientId: 101,
    doctorId: 176897,
    patientName: "Ravi Kumar",
    date: "2025-08-15",
    diagnosis: "Hypertension",
    treatment: "Started on antihypertensive medication",
    status: "FOLLOWUP_NEEDED",
  },
  {
    id: 2,
    consultationId: "cons002",
    patientId: 102,
    doctorId: 176897,
    patientName: "Priya Sharma",
    date: "2025-08-17",
    diagnosis: "Cardiac arrhythmia",
    treatment: "Beta blocker therapy initiated",
    status: "FOLLOWUP_NEEDED",
  },
  {
    id: 3,
    consultationId: "cons003",
    patientId: 103,
    doctorId: 202032,
    patientName: "Amit Patel",
    date: "2025-08-14",
    diagnosis: "Acute sinusitis",
    treatment: "Antibiotics and decongestants",
    status: "COMPLETED",
  },
  {
    id: 4,
    consultationId: "cons004",
    patientId: 104,
    doctorId: 302032,
    patientName: "Neha Gupta",
    date: "2025-08-18",
    diagnosis: "Allergic contact dermatitis",
    treatment: "Topical steroids and antihistamines",
    status: "COMPLETED",
  },
  {
    id: 5,
    consultationId: "cons005",
    patientId: 107,
    doctorId: 202032,
    patientName: "Vikram Singh",
    date: "2025-08-12",
    diagnosis: "Conductive hearing loss",
    treatment: "Further imaging required",
    status: "FOLLOWUP_NEEDED",
  },
  {
    id: 6,
    consultationId: "cons006",
    patientId: "HO132",
    doctorId: 502032,
    patientName: "Jane",
    date: "2025-08-16",
    diagnosis: "Post-viral cough",
    treatment: "Symptomatic treatment with cough suppressant",
    status: "COMPLETED",
  },
  {
    id: 7,
    consultationId: "cons007",
    patientId: "HO132",
    doctorId: 502032,
    patientName: "Jane",
    date: "2025-07-10",
    diagnosis: "Viral pharyngitis",
    treatment: "Supportive care with antipyretics",
    status: "COMPLETED",
  },
];

export const notifications = [
  {
    id: 1,
    userId: 101,
    message:
      "Your appointment with Dr. Asha Singh on Aug 15 at 10:00 is confirmed.",
    read: false,
    type: "APPOINTMENT_CONFIRMATION",
    timestamp: "2025-08-10T09:30:00Z",
  },
  {
    id: 2,
    userId: 101,
    message: "Dr. Laxman Sinha has updated your prescription.",
    read: true,
    type: "PRESCRIPTION_UPDATE",
    timestamp: "2025-07-16T14:25:00Z",
  },
  {
    id: 3,
    userId: 102,
    message:
      "Your appointment request with Dr. Emily Carter is pending approval.",
    read: false,
    type: "APPOINTMENT_PENDING",
    timestamp: "2025-08-11T11:15:00Z",
  },
  {
    id: 4,
    userId: 103,
    message: "Your appointment with Dr. Adam Smith has been completed.",
    read: true,
    type: "APPOINTMENT_COMPLETED",
    timestamp: "2025-08-14T12:45:00Z",
  },
  {
    id: 5,
    userId: 104,
    message: "New test results are available for your review.",
    read: false,
    type: "TEST_RESULTS",
    timestamp: "2025-08-15T16:30:00Z",
  },
  {
    id: 6,
    userId: "HO132",
    message:
      "Your consultation with Dr. Smith has been completed. Prescription available.",
    read: false,
    type: "CONSULTATION_COMPLETED",
    timestamp: "2025-08-16T12:00:00Z",
  },
  {
    id: 7,
    userId: "HO132",
    message: "Your follow-up appointment is scheduled for August 23, 2025.",
    read: false,
    type: "FOLLOWUP_REMINDER",
    timestamp: "2025-08-16T12:30:00Z",
  },
  {
    id: 101,
    userId: 176897, // Dr. Elina Josh
    message:
      "You have a new appointment scheduled with Ravi Kumar on Aug 15 at 10:00.",
    read: false,
    type: "NEW_APPOINTMENT",
    timestamp: "2025-08-14T08:00:00Z",
  },
  {
    id: 102,
    userId: 176897,
    message: "Patient Sunita Yadav has requested a prescription update.",
    read: false,
    type: "PRESCRIPTION_REQUEST",
    timestamp: "2025-08-15T09:30:00Z",
  },
  {
    id: 103,
    userId: 276567, // Dr. Laxman Sinha
    message: "Your appointment with Ravi Kumar is pending approval.",
    read: false,
    type: "APPOINTMENT_PENDING",
    timestamp: "2025-08-16T10:00:00Z",
  },
  {
    id: 104,
    userId: 102032, // Dr. Emily Carter
    message: "Priya Sharma has uploaded new test results for review.",
    read: false,
    type: "TEST_RESULTS",
    timestamp: "2025-08-17T11:00:00Z",
  },
  {
    id: 105,
    userId: 202032, // Dr. Mia Mike
    message: "Amit Patel has completed his follow-up appointment.",
    read: false,
    type: "FOLLOWUP_COMPLETED",
    timestamp: "2025-08-18T12:00:00Z",
  },
  {
    id: 106,
    userId: 302032, // Dr. Adam Smith
    message:
      "Neha Gupta has sent a message regarding her skin allergy treatment.",
    read: false,
    type: "PATIENT_MESSAGE",
    timestamp: "2025-08-19T13:00:00Z",
  },
  {
    id: 107,
    userId: 402032, // Dr. Asha Sing
    message: "Rajesh Verma has cancelled his appointment scheduled for Aug 13.",
    read: false,
    type: "APPOINTMENT_CANCELLED",
    timestamp: "2025-08-13T14:00:00Z",
  },
];
